//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project1.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    public partial class Attendance
    {
        public int Std_ID { get; set; }
        public int Teach_ID { get; set; }
        public int Course_ID { get; set; }
        public string Attendance1 { get; set; }
        public Nullable<System.DateTime> Date { get; set; }

        [JsonIgnore]
        [IgnoreDataMember]
        public virtual Cours Cours { get; set; }
        [JsonIgnore]
        [IgnoreDataMember]
        public virtual Student Student { get; set; }
        [JsonIgnore]
        [IgnoreDataMember]
        public virtual Teacher Teacher { get; set; }
    }
}
